String examples
DiffBlue-benchmarks/java-test pull request #15
Opened 2017-04-28 13:16 UTC by rjmunro

Example string functions based on the regression tests to generate tests for.

2017-05-03 15:40 UTC, peterjwest commented on diffblue.yml
> +  refine-strings: true
I suggest we don't add this here, but wait for platform to be updated with it instead

2017-05-03 15:42 UTC, peterjwest commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +public class StringStuff {
How about "Strings", let's not slip back into rubbish naming

2017-05-03 15:43 UTC, peterjwest commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +  public static String classGetNameExample(Class c) {
I think "Example" is redundant in the method name, this entire repository is examples

2017-05-03 15:45 UTC, peterjwest commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +  public static String classGetNameExample(Class c) {
Can we avoid non-descriptive and one letter variable names? If people are using this a lot it should be easy to follow.

2017-05-03 15:48 UTC, peterjwest commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +  public static int checkHtml2(String s) {
Can this be named to more clearly distinguish between `checkHtml`?

2017-05-03 15:48 UTC, thisjunewest requested changes
Please lint this (see README.md)

2017-05-03 16:04 UTC, rjmunro commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +  public static String classGetNameExample(Class c) {
@peterjwest The problem is that the names then become very close or identical to the things they are using.

2017-05-03 16:05 UTC, rjmunro commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +public class StringStuff {
Strings is rubbish as well - StringExamples or something would be better.

2017-05-03 16:06 UTC, rjmunro commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +  public static String classGetNameExample(Class c) {
The method bodies all come directly from the regression tests on CBMC - I'd rather leave them as is.

2017-05-03 16:08 UTC, peterjwest commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +  public static String classGetNameExample(Class c) {
Is that a problem?

2017-05-03 16:08 UTC, peterjwest commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +  public static String classGetNameExample(Class c) {
I disagree, we're going to have to be looking through the trace debugging these, "s" and "c" aren't helpful.

2017-05-03 16:14 UTC, rjmunro commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +  public static int checkHtml2(String s) {
I've removed it as it was hard to find in the original regression tests.

2017-05-03 16:34 UTC, rjmunro commented
The linter wants me to add javadoc for every function, and make other changes that make the function bodies different to the originals. I'm not sure.

2017-05-04 10:15 UTC, royletron commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +public class StringStuff {
I'm with @rjmunro

2017-05-04 10:16 UTC, royletron commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +  public static String classGetNameExample(Class c) {
This time I am with @peterjwest

2017-05-09 16:45 UTC, peterjwest commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +public class StringStuff {
StringExamples is ok

2017-06-07 16:47 UTC, sara-db commented
@forejtv please review

2017-06-14 15:48 UTC, forejtv approved these changes
See my comments, ow looks good.

2017-06-14 15:48 UTC, forejtv commented on diffblue.yml
> +  refine-strings: true
@rjmunro has this already happened and can the line be removed?

2017-06-14 15:48 UTC, forejtv commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +public class StringStuff {
Yes, let's go with StringExamples

2017-06-14 15:48 UTC, forejtv commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +  public static String classGetNameExample(Class c) {
I'm happy to keep `Example` as part of the name, so this is fine by me.

2017-06-14 15:48 UTC, forejtv commented on main-module/src/main/java/com/diffblue/javatest/StringStuff.java
> +  public static String classGetNameExample(Class c) {
I'd say let's leave it as it is for now. If this becomes a problem let's modify it.

2017-07-06 12:50 UTC, peterjwest commented
Closing as superseded by #18

2017-07-06 12:50 UTC, closed without merging